### ISSUE TITLE
Collapsing and uncollapsing trees

### ISSUE THREAD

**Issue by chds718** [zward/Amua#1]
It would be cool if the program remembered the nodes that were collapsed and progressively uncollapsed them.. Say I have 3 levels of branches emanating from the source(decision) node. Lets say I collapse a node deep in the tree (far to the right). Then I also collapse a node more to the left. Now when I uncollapse the node, it uncollapses EVERYTHING. it would be better if it just uncollapsed enough to make it look like it did at the time it was collapsed (in other words, the first node I collapsed to the far right would still be collapsed).

**Comment by zward** [comment]
Fixed as of 0.0.8
Save collapsed status of nodes to file.  Also added nested collapsing
