### ISSUE TITLE
copy/paste is not working (MAC)

### ISSUE THREAD

**Issue by liembinh** [zward/Amua#15]

**Comment by zward** [comment]
I think this is resolved, so closing this issue.

**Comment by liembinh** [comment]
It kind of is. It is just that for copy/paste I need to do ctrl + C/V, but to save, I do cmd +S. This is minor bug but worth saying for Mac users

**Comment by zward** [comment]
Do you still have this issue with the latest version of Amua?
Also, what version of Java are you using?  I just tried on Java 10.0.2 on Mac OS X and copy/paste with cmd works.

**Comment by liembinh** [comment]
Hi Zach,

copy/paste with cmd does not work, but with ctrl it does work.

Liem
