### ISSUE TITLE
Multiplying probabilities with number of times a certain pathway is taken.

### ISSUE THREAD

**Issue by svengoetstouwers** [zward/Amua#36]
Dear Zach,

Amua is great, so first thanks for that! I only have a question:
I simulate a group of patients (with Monte-Carlo microsimulation) who have an aneurysm (see image). 
Each year, this person can either have an aneurysm rupture, no rupture or they can develop another aneurysm. What I want is that the probability of aneurysm rupture is dependent on how many aneurysms the patient has. So for example, if the probability of rupture is 0.02, that it would be twice that for someone with 2 aneurysms. What I can do is make multiple health states for this, but this would become very inefficient and chaotic. Is there a possibility to track the amount of times a person has gone through a certain pathway (i.e. the amount of times a patient has developed a new aneurysm) and to use this for the probability of entering another pathway ('rupture = # x normal risk' in the image)? 

![image](https://user-images.githubusercontent.com/52659808/60806720-0a2d3280-a184-11e9-9e6d-683cfb4d0186.png)

**Comment by zward** [comment]
If I understand correctly, I think you could could create a variable (e.g. `numAneurysm`) and add a variable update to the New aneurysm event `numAneurysm++` which keeps track of the number of new aneurysms an individual experiences.  The the probability of rupture could depend on `numAneurysm`.
