### ISSUE TITLE
UTF8 / ASCI

### ISSUE THREAD

**Issue by TJA87** [zward/Amua#44]
Hello,

I keep having an issue where I get an "error: null" error when I try to open previous models. 

I have to use Notepad++ to convert files back to UTF8 every time I want to open them. Do you have any way to have the files stay as UTF8? As far as I know, there are no special characters within them.

Thanks!

**Comment by zward** [comment]
The models should always be saved as UTF-8: there is a line of code that explicitly specifies the encoding before writing to file.  But I wonder if there is something in the model that triggers ASCI in the Java XML marshaller.
Can you send me a copy of a model where you have problems (zward@hsph.harvard.edu) so I can test it on my system?  Thanks

**Comment by zward** [comment]
UTF-8 encoding should be fixed as of v0.2.8
