### ISSUE TITLE
Discrepancy between CEA results overall and on individual level

### ISSUE THREAD

**Issue by svengoetstouwers** [zward/Amua#47]
There seems to be a discrepancy between the results of the CEA overall and on individual level. If I look at the overall results, I see that Intervention is most cost-effective with the WTP that I have, with an ICER of 7924,4499, but that 'every 2 years' is weakly dominated:
![image](https://user-images.githubusercontent.com/52659808/75326800-914a2a80-587b-11ea-8c2d-84d423f771fc.png)

However, if I look at the individual results, I see that 'every 2 years' has both better QALYs and lower costs:
![image](https://user-images.githubusercontent.com/52659808/75327033-0158b080-587c-11ea-873a-baaed3cf72a1.png)
![image](https://user-images.githubusercontent.com/52659808/75327062-0b7aaf00-587c-11ea-82a2-1dbdaf45bba6.png)

So my question is: shouldn't 'every 2 years' be the strategy with the best ICER rather than 'Intervention'?

Thanks in advance!

**Comment by zward** [comment]
Yes, that does look strange. Is this with the latest version (0.2.8)?
Can you send me a copy of the model (zward@hsph.harvard.edu) so I can test it?

**Comment by svengoetstouwers** [comment]
Yes it is in 0.2.8. I will send you a copy of the model.

**Comment by zward** [comment]
Individual-level half-correction correction fixed as of v0.2.9
