### ISSUE TITLE
Transitional probability using Weibull survival

### ISSUE THREAD

**Issue by yangszuchun** [zward/Amua#48]
Excuse me! I have the lambda and gamma values (as well as the intercept and log(scale)) of Weibull survival, how to input the shape and scale parameters in your Weibull distribution to derive the transitional probability?

Thank you in advance!

**Comment by zward** [comment]
The Weibull distribution in Amua is based on equations 1 and 2 here: https://mathworld.wolfram.com/WeibullDistribution.html

There are a few different parameterizations though - how are you estimating the parameters?  You should be able to convert them to match the functional form in the link above.  
I would plot the distribution (Tools -> Plot Function): `Weibull(x,a,b,f)` and check the mean `Weibull(a,b,E)` to make sure you are converting the parameters correctly.

**Comment by yangszuchun** [comment]
Thank you for the reply! The problem has been solved. Your Plot Function are useful!
