### ISSUE TITLE
Model gets stuck

### ISSUE THREAD

**Issue by fawaz91** [zward/Amua#49]
Hi,
A recent issue has been is whenever i return to my saved model it does not allow me to make changes and if add nodes it would continue to work but it would not adjust to it. The probelm occurs if i return to saved model after reopening it later on Mac.

Best
Fawaz

**Comment by zward** [comment]
Hi Fawaz,
I'm not sure I completely understand the problem...  Are you trying to make changes to the model while a simulation is still running?
Can you provide more details, or send me a copy of the model (zward@hsph.harvard.edu) so I can see if it works on another computer?

**Comment by fawaz91** [comment]
Hi,
I hadnt completed my model was just making nodes and saved it. When i
reopened it it it wont let me add more nodes or branches. I will attach the
model

**Comment by fawaz91** [comment]
Sent

**Comment by zward** [comment]
Opening model with no Markov states attached to a Markov chain fixed as of v0.2.9
