### ISSUE TITLE
A unit time for each cycle is 1.5 month but a result using year (i.e., 12 month) as the denominator

### ISSUE THREAD

**Issue by yangszuchun** [zward/Amua#50]
Excuse me! If the unit time for each cycle is 1.5 month (6 weeks) but I would like to get a result using life year or QALY (i.e., 12 month instead of 1.5 month) as the denominator, how to adjust the property Amua?
Thank you very much in advance!

**Comment by zward** [comment]
You should be able to use any cycle length, as long as you convert the transition probabilities and rewards.  Annual transition probabilities need to be re-scaled to match up with the new cycle length - you can use the `probRescale` function.  To calculate QALYs you would change the rewards from 1.0 to 1/cycles per year.  So moving from a one-year cycle to a one-month cycle you would divide all of the rewards by 12, for example.  
Does this answer your question?

**Comment by yangszuchun** [comment]
Thank you for the kindest reply! I am sorry that I did not explain very well.
I used 1.5 months as a unit, and the ICER was $37140/1.5 months (as below and attached).
CEA Results (Ratio of Means):Strategy             Cost        QALY    ICER       Notes   -------------------- ----------- ------- ---------- --------Chemotherapy         192743.8503 11.7906        --- BaselineNivolumab+Ipilimumab  494098.828 19.9045 37140.3972 
But I would like to have a result of  37140x8/12 months (like that in the scatter plot). How to solve the problem?Again, thank you for your kindness!
Best,Szu-Chun    在 2020年3月16日 星期一 上午08:25:04 [EDT]， Zach Ward<notifications@github.com> 寫道：  
 
 


You should be able to use any cycle length, as long as you convert the transition probabilities and rewards. Annual transition probabilities need to be re-scaled to match up with the new cycle length - you can use the probRescale function. To calculate QALYs you would change the rewards from 1.0 to 1/cycles per year. So moving from a one-year cycle to a one-month cycle you would divide all of the rewards by 12, for example.
Does this answer your question?

**Comment by zward** [comment]
Hi Szu-Chun,
I'm still not sure I understand what you are trying to do.  I don't see a scatter plot either. Do you want to send me a copy of the model (zward@hsph.harvard.edu) and describe what the problem is?
