### ISSUE TITLE
CEAC

### ISSUE THREAD

**Issue by Tiarisma** [zward/Amua#52]
Thanks for your work on amua! I really appreciate it. However, I have an inquiry regarding CEAC. I want to do a Markov model and I have four decisions (treatments) and three outcomes for each treatment. I have been trying to run CEAC analysis but my curve not appear.  Thank you in advanced.

**Comment by zward** [comment]
What do your ICER results look like in the Results tab, or Scatterplot?  Can you send me a screenshot of the CEAC tab along with the other PSA results? (You can post it here or send via e-mail: zward@hsph.harvard.edu)

**Comment by Tiarisma** [comment]
Hello Sir,

Thank you for reaching me out. I really appreciate it.  As per my inquiry
on CEAC, the run result not appear and just a blank graph without a CEAC
curve.

A brief explanation of my study, I am doing a study on the
cost-effectiveness of psoriasis treatment and using the Markov model for my
research method.  For my study, I have 4 treatments decision. Each
treatment has three outcomes (three states).    Thank you for your
consideration and I hope to hear from you soon. I really appreciate it and
thank you.

I enclose my result for the CEAC graph as per your request.

Regards,

*NURUL FATIHA RISMA BINTI RISMAYUDDIN*
nfrisma@gmail.com
