### ISSUE TITLE
Issue opening .amua files

### ISSUE THREAD

**Issue by WinkelJordi** [zward/Amua#55]
Dear reader,

I used the following to guides to install Amua on a Mac:

https://canvas.eur.nl/courses/37459/pages/0-required-software?module_item_id=708679 
https://github.com/zward/Amua/wiki

I previously worked on a Markov model but struggle opening it. It basically says the file cannot be opened by the java app or by the amua.jar file. I cannot find someone who had a similar issue online. Does anyone know how to fix this?

Best,
Jordi

**Comment by zward** [comment]
If you send me a copy of your file (zward@hsph.harvard.edu) I can take a look and see what the issue might be.

**Comment by zward** [comment]
This seems to be an issue on some Macs where the .amua files are not visible when browsing the file system from Amua.  Moving the files to the Applications folder resolves this problem though and allows .amua files to be saved and re-opened.
