### ISSUE TITLE
cannot run model anymore

### ISSUE THREAD

**Issue by MMP24** [zward/Amua#59]
Hi Zach,

Since this afternoon, I'm suddenly no longer able to run my model, check my tree, run scenarios, export data. Essentially I cannot do anything anymore.

The java error says: 
Tue Jan 10 00:53:39 CET 2023
java.lang.NullPointerException
Message: null
Trace:
tree.DecisionTree.parseTree(DecisionTree.java:205)
base.AmuaModel.parseModel(AmuaModel.java:810)
gui.frmScenarios$15$1.run(frmScenarios.java:629)

Any solution to this?

**Comment by zward** [comment]
Looks like the model is trying to parse variable updates for a node, but that the updates are empty.  Is there an empty variable updates textbox attached to one of the nodes?

**Comment by zward** [comment]
If you send me a copy of your model (zward@hsph.harvard.edu) I can debug and see what's going on

**Comment by zward** [comment]
There was an empty variable updates textbox causing the error, but it was attached to a node in a collapsed branch, making it difficult to see.  One workaround is to go into the .amua file and find "<hasVarUpdates>true</hasVarUpdates>" and change it to "<hasVarUpdates>false</hasVarUpdates>" where needed.  I will also change the code for the next release to check for this when parsing the tree.
