### ISSUE TITLE
Font scaling

### ISSUE THREAD

**Issue by chds718** [zward/Amua#8]
There is an issue with the font scaling. The UI fonts get very tiny on modern hi-res monitors with dense DPI. Windows has "scaling" feature to address this, but it doesn't affect the Java app. Maybe there is a 3rd party solution for this, as I imagine other Java apps with UI have the same issue.

**Comment by chds718** [comment]
https://superuser.com/questions/988379/how-do-i-run-java-apps-upscaled-on-a-high-dpi-display

**Comment by chds718** [comment]
NOTE: I found an obvious workaround, which is adjusting my monitors resolution down from 3840x2160 to 2048x1152. At that level I can read the menus and tables OK. But still its something to consider fixing. There must be a Java solution for this---you shouldn't have to reinvent the wheel.

**Comment by zward** [comment]
This should be fixed for Java 1.9 and newer
