### ISSUE TITLE
FileOpen Dialog memory

### ISSUE THREAD

**Issue by chds718** [zward/Amua#9]
It might be good to have the FileOpen dialog automatically go to the folder in which the Amua.jar resides. That way users can put the Amua.jar in the folder (or parent folder) for the location where they want to store their Amua files, and then navigating to those files will be a whole lot easier.

**Comment by zward** [comment]
The Model -> Open Recent feature should address this.  As long as the jar is in the same location as the _recentFiles file you should be able to quickly open recently used models.
